application: uvalibapi
version: new
runtime: python27
threadsafe: true
api_version: 1

builtins:
- deferred: on

handlers:
# Deferred handler
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

# Endpoints handler
- url: /_ah/spi/.*
  script: uvalibrary_api.APPLICATION

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?test_runner.py
- ^(.*/)tests.*